// GENERATED by scripts/build_ps_battlefield.py — 手で編集しない。
// PS正本クロップから導出した戦場キャンバス(背景画像 + 30hex地形)。
window.PS_BATTLEFIELDS = {
  "ps_seed_1001": {
    "name": "ps_seed_1001",
    "image": "ps_seed_1001.png",
    "imageWidth": 620,
    "imageHeight": 620,
    "projection": {
      "scale": 0.84,
      "topLeftX": 885.3516092068122,
      "topLeftY": 509.1
    },
    "rows": [
      [
        7,
        7,
        [
          "FOREST",
          "BLDG",
          "ROAD",
          "BLDG",
          "GRASS"
        ]
      ],
      [
        8,
        6,
        [
          "FOREST",
          "GRASS",
          "ROAD",
          "FIELD",
          "GRASS"
        ]
      ],
      [
        9,
        6,
        [
          "FOREST",
          "ROAD",
          "BLDG",
          "FIELD",
          "FIELD"
        ]
      ],
      [
        10,
        5,
        [
          "GRASS",
          "ROAD",
          "GRASS",
          "FIELD",
          "FIELD"
        ]
      ],
      [
        11,
        5,
        [
          "BLDG",
          "ROAD",
          "GRASS",
          "GRASS",
          "FIELD"
        ]
      ],
      [
        12,
        4,
        [
          "GRASS",
          "FOREST",
          "ROAD",
          "FOREST",
          "FIELD"
        ]
      ]
    ]
  },
  "ps_seed_2026": {
    "name": "ps_seed_2026",
    "image": "ps_seed_2026.png",
    "imageWidth": 620,
    "imageHeight": 620,
    "projection": {
      "scale": 0.84,
      "topLeftX": 885.3516092068122,
      "topLeftY": 509.1
    },
    "rows": [
      [
        7,
        7,
        [
          "ROAD",
          "FIELD",
          "FIELD",
          "FIELD",
          "GRASS"
        ]
      ],
      [
        8,
        6,
        [
          "ROAD",
          "FIELD",
          "GRASS",
          "FIELD",
          "FOREST"
        ]
      ],
      [
        9,
        6,
        [
          "ROAD",
          "FIELD",
          "GRASS",
          "GRASS",
          "GRASS"
        ]
      ],
      [
        10,
        5,
        [
          "BLDG",
          "ROAD",
          "BLDG",
          "GRASS",
          "FOREST"
        ]
      ],
      [
        11,
        5,
        [
          "ROAD",
          "GRASS",
          "GRASS",
          "GRASS",
          "GRASS"
        ]
      ],
      [
        12,
        4,
        [
          "ROAD",
          "GRASS",
          "FOREST",
          "GRASS",
          "FOREST"
        ]
      ]
    ]
  },
  "ps_village_north": {
    "name": "ps_village_north",
    "image": "ps_village_north.png",
    "imageWidth": 620,
    "imageHeight": 620,
    "projection": {
      "scale": 0.84,
      "topLeftX": 885.3516092068122,
      "topLeftY": 509.1
    },
    "rows": [
      [
        7,
        7,
        [
          "ROAD",
          "BLDG",
          "ROAD",
          "BLDG",
          "GRASS"
        ]
      ],
      [
        8,
        6,
        [
          "ROAD",
          "FIELD",
          "ROAD",
          "FOREST",
          "GRASS"
        ]
      ],
      [
        9,
        6,
        [
          "GRASS",
          "FIELD",
          "GRASS",
          "FIELD",
          "FIELD"
        ]
      ],
      [
        10,
        5,
        [
          "BLDG",
          "FOREST",
          "GRASS",
          "FIELD",
          "GRASS"
        ]
      ],
      [
        11,
        5,
        [
          "FIELD",
          "ROAD",
          "GRASS",
          "GRASS",
          "BLDG"
        ]
      ],
      [
        12,
        4,
        [
          "FIELD",
          "ROAD",
          "GRASS",
          "GRASS",
          "FIELD"
        ]
      ]
    ]
  }
};
