#!/usr/bin/env python3
"""PL正本の武器統計から、シムが使う分だけを切り出してランタイムへ載せる。

なぜ要るか（2026-08-03）:
  data/wpns_pl_stats_decoded.json には銃ごとの
  「初期命中率 / 命中低下率 / ゼロ距離貫通力 / 貫通低下率 / 連射数 / 白兵攻撃力」が
  455挺ぶん入っている（GPT-5.6 の PL正本総ざらいの成果）。ところが sim_core は
  これを一切参照せず、**クラス別の定数4種**(PHIT_BASE)と**全武器一律の威力**
  (DMG_HIT 40±20)で撃っていた。ルガーとガーランドの基本命中が同じで、
  1斉射が何発でも命中判定は1回、という状態だった。

  PL正本のモデルでは **`dmg` は白兵専用の攻撃力**であって、弾丸の威力は
  「貫通力とその距離低下」で表される（当たれば必ず効く。どれだけ効くかが貫通力）。
  ここではそのモデルをそのまま持ち込む。

出力: data/pl_weapon_stats.js (window.PL_WEAPON_STATS / module.exports)
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "wpns_pl_stats_decoded.json"
OUT = ROOT / "data" / "pl_weapon_stats.js"

# 旧来の手書き WPNS コード -> PL正本コード。
# 名前一致は当てにならない（"Luger P08" と "P08"、"Colt M1911" と "M1911A1"）ので
# 実データを引いて確認した対応だけを明示的に置く。解決しないコードは
# 従来のクラス別既定値へフォールバックする（壊さないため）。
ALIAS = {
    "m1": "pl_8",           # M1 Garand      -> M1 Rifle
    "k98_scope": "pl_6",    # M1903 Scope    -> M1903A4（狙撃型）
    "bar": "pl_7",          # M1918 BAR      -> M1918A2 BAR
    "m1911": "pl_0",        # Colt M1911     -> M1911A1
    "luger": "pl_43",       # Luger P08      -> P08
    "thompson": "pl_17",    # M1A1 SMG       -> M1A1 SMG
    "mg42": "pl_402",       # MG42           -> MG42(mg)
    "kwk": "pl_417",        # 75mm KwK       -> 75mmGun M3
    "m8_rocket": "pl_25",   # M8 Rocket      -> M1 RL（バズーカ）
}

FIELDS = {
    "acc": "initial_hit_rate",
    "accDrop": "hit_decay_rate",
    "pen": "initial_penetration",
    "penDrop": "penetration_decay_rate",
    "shots": "shots_per_action",
    "melee": "melee_attack",
    "malf": "malfunction_rate",
}


def main() -> None:
    raw = json.loads(SRC.read_text(encoding="utf-8"))
    entries = raw.values() if isinstance(raw, dict) else raw
    out: dict[str, dict] = {}
    for entry in entries:
        code = entry.get("wpns_code")
        if not code:
            continue
        rec = {}
        for key, src_key in FIELDS.items():
            v = entry.get(src_key)
            if v is not None:
                rec[key] = v
        if entry.get("auto_fire"):
            rec["auto"] = 1
        if entry.get("plCategory"):
            rec["cat"] = entry["plCategory"]
        # 命中も貫通も0の項目（装備品・弾薬箱）は銃ではないので載せない
        if not rec.get("acc") and not rec.get("pen"):
            continue
        out[code] = rec

    missing = [k for k, v in ALIAS.items() if v not in out]
    if missing:
        raise SystemExit(f"別名の参照先が統計に無い: {missing}")

    lines = [
        "// GENERATED by scripts/build_pl_weapon_stats.py — 手で編集しない。",
        "// PL正本の武器統計（data/wpns_pl_stats_decoded.json）のうち、シムが使う分。",
        "//   acc/accDrop  初期命中率と1ヘックスあたりの命中低下",
        "//   pen/penDrop  ゼロ距離貫通力と1ヘックスあたりの貫通低下（＝弾丸の威力とその減衰）",
        "//   shots/auto   1動作の発射弾数・全自動か",
        "//   melee        白兵専用の攻撃力（弾丸の威力ではない）",
        "// ブラウザは globalThis(=window) へ、node は module.exports へ載る。",
        "(function (root) {",
        "  var STATS = {",
    ]
    for code in sorted(out, key=lambda c: (len(c), c)):
        rec = out[code]
        body = ", ".join(f"{k}: {json.dumps(v)}" for k, v in rec.items())
        lines.append(f'    "{code}": {{{body}}},')
    lines.append("  };")
    lines.append("  // 旧来の手書きコード -> PL正本コード")
    alias_body = ", ".join(f'"{k}": "{v}"' for k, v in sorted(ALIAS.items()))
    lines.append(f"  var ALIAS = {{{alias_body}}};")
    lines.append("  root.PL_WEAPON_STATS = STATS;")
    lines.append("  root.PL_WEAPON_STATS_ALIAS = ALIAS;")
    lines.append("  if (typeof module !== 'undefined' && module.exports) {")
    lines.append("    module.exports = { PL_WEAPON_STATS: STATS, PL_WEAPON_STATS_ALIAS: ALIAS };")
    lines.append("  }")
    lines.append("})(typeof globalThis !== 'undefined' ? globalThis : this);")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    cats: dict[str, int] = {}
    for rec in out.values():
        cats[rec.get("cat", "?")] = cats.get(rec.get("cat", "?"), 0) + 1
    print(f"{OUT.relative_to(ROOT)}: {len(out)} 挺 / 別名 {len(ALIAS)}")
    print("  カテゴリ:", ", ".join(f"{k}={v}" for k, v in sorted(cats.items())))


if __name__ == "__main__":
    main()
