#!/usr/bin/env python3
"""立体物台帳(*_objects.json)から、ヘックス単位の遮光度・遮蔽の加算修正を導出する。

なぜ要るか（2026-08-03 実測）:
  ps_battlefields.js の地形は **1ヘックス＝1種別の単値**（GRASS/FOREST/ROAD/FIELD/BLDG）
  なので、台帳が持っている低木70個・柵27個といった情報がまるごと捨てられていた。
  結果、盤面の83%が草原・射程内ペアの81%が素通しになり、
  「全員が全員を見通せる平原」＝機動する理由が無い盤面になっていた。

  地形の**種別は絵と意味の担当**として残したまま、台帳から per-hex の加算modを
  重ねる。台帳は描画が実際に使っている座標そのものなので、**絵と地形が必ず一致する**
  （手で森林ヘックスを足すと「芝生に見える場所で兵士が隠れる」ことになる）。

出力: asset/environment/maps/ps_terrain_mods.js (window.PS_TERRAIN_MODS)
      { "<map key>": { "q,r": [sightBlock, coverBonus], ... }, ... }

値の根拠: 規則候補ごとに14マップの遮蔽率を実測して選んだ（規則C）。
  現状12.0% / 木のみ21.1% / +低木29.1% / **+柵・薪 33.4%** / 木1本で遮る33.8%。
  木を「1本で遮る」に強めても結果がほぼ変わらない（木のヘックスは元々2本以上ある）ため、
  既存の「1枚は透け、2枚重なると遮る」設計を保つ規則Cを採用した。
  参考: 市街マップは約60%、旧30hexビネットは約17%。
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPS = ROOT / "asset" / "environment" / "maps"
OUT = MAPS / "ps_terrain_mods.js"

# family -> (1個あたりの遮光度, 遮光度の上限, 1個あたりの遮蔽, 遮蔽の上限)
RULES = {
    "tree":  (0.5,  1.0,  8, 20),
    "shrub": (0.25, 0.5,  5, 15),
    "fence": (0.25, 0.25, 10, 10),
    "prop":  (0.25, 0.5,  8, 12),   # 薪の山・荷車・井戸。麦畑は地形FIELD側の担当
}
# large_prop のうち「立って視界を遮る物」だけを prop として数える。
# wheat_* は作物＝地形FIELD、washing/sunflower は視界を遮らない。
PROP_ASSETS = ("woodpile", "cart", "well")
COVER_CAP = 45      # 廃屋(40)・建物を超えないための上限
BLOCK_CAP = 1.0     # 1ヘックスで完全遮蔽が上限（LOS_BLOCK_THRESHOLD と同値）


def family_of(obj: dict) -> str | None:
    fam = obj.get("family")
    if fam in ("tree", "shrub", "fence"):
        return fam
    if fam == "large_prop":
        asset = obj.get("asset", "")
        return "prop" if any(p in asset for p in PROP_ASSETS) else None
    return None   # building は地形BLDGが担当、それ以外は視界に無関係


def derive(ledger: dict) -> dict[str, list]:
    per: dict[tuple[int, int], Counter] = {}
    for obj in ledger.get("objects", []):
        hex_ = obj.get("hex")
        fam = family_of(obj)
        if not hex_ or fam is None:
            continue
        per.setdefault((hex_[0], hex_[1]), Counter())[fam] += 1

    mods: dict[str, list] = {}
    for (q, r), counts in sorted(per.items()):
        block = 0.0
        cover = 0
        for fam, n in counts.items():
            per_block, block_cap, per_cover, cover_cap = RULES[fam]
            block += min(block_cap, n * per_block)
            cover += min(cover_cap, n * per_cover)
        block = round(min(BLOCK_CAP, block), 3)
        cover = int(min(COVER_CAP, cover))
        if block <= 0 and cover <= 0:
            continue
        mods[f"{q},{r}"] = [block, cover]
    return mods


def main() -> None:
    out: dict[str, dict] = {}
    for path in sorted(MAPS.glob("*_objects.json")):
        key = path.name[: -len("_objects.json")]
        ledger = json.loads(path.read_text(encoding="utf-8"))
        mods = derive(ledger)
        if mods:
            out[key] = mods

    lines = [
        "// GENERATED by scripts/derive_terrain_mods.py — 手で編集しない。",
        "// 立体物台帳(*_objects.json)から導出した、ヘックス単位の遮光度・遮蔽の加算修正。",
        "// 地形の種別(ps_battlefields.js)は単値なので、低木や柵の情報がそこには乗らない。",
        "// 描画が使っている座標そのものから導くので、絵と地形が必ず一致する。",
        "// 形式: { \"<map key>\": { \"q,r\": [sightBlock, coverBonus] } }",
        "window.PS_TERRAIN_MODS = {",
    ]
    for key in sorted(out):
        entries = ", ".join(f'"{h}": [{v[0]}, {v[1]}]' for h, v in sorted(out[key].items()))
        lines.append(f'  "{key}": {{{entries}}},')
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    total = sum(len(v) for v in out.values())
    print(f"{OUT.relative_to(ROOT)}: {len(out)} マップ / 修正ヘックス {total}")
    for key in sorted(out):
        blocks = [v[0] for v in out[key].values()]
        full = sum(1 for b in blocks if b >= BLOCK_CAP)
        print(f"  {key:<18} 修正hex {len(out[key]):3d}  うち単独で遮る {full:2d}")


if __name__ == "__main__":
    main()
