#!/usr/bin/env python3
"""生成済みのHD地面(2x)を本編アセットへ昇格する。

`rebuild_all_ps_ground_hd.py` は output/ground_hd_maps へ出力するだけで、本編の
asset/environment/maps へは入れない。本スクリプトがその「昇格」だけを担う。

やること:
  1. output/ground_hd_maps/*_ground_hd_x2.png を asset/environment/maps へコピー
  2. asset/environment/maps/ps_battlefields.js の各エントリを差し替える
     - image      -> <name>_ground_hd_x2.png
     - pixelRatio -> 2
     - name / projection / rows は据え置き（**論理座標は不変**）

重要: HD PNG は物理2倍だが、imageWidth/Height と projection は論理値のまま扱う。
HDだからと origin や topLeft を2倍してはいけない（PS_TREE_RENDERING_RE_HANDOFF.md
の「Claudeがゲーム側で行うこと」項4）。本スクリプトは投影が一致しない場合に中断する。

例:
    python scripts/promote_ground_hd_to_game.py --dry-run
    python scripts/promote_ground_hd_to_game.py
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


HD_SUFFIX = "_ground_hd_x2"
HEADER = (
    "// GENERATED by scripts/build_ps_battlefield.py — 手で編集しない。\n"
    "// PS正本クロップから導出した戦場キャンバス(背景画像 + 30hex地形)。\n"
    "// HD地面(2x)は scripts/promote_ground_hd_to_game.py が昇格させる。\n"
    "// imageWidth/Height と projection は論理値。pixelRatio=2 の実PNGは物理2倍。\n"
)
ASSIGN = "window.PS_BATTLEFIELDS = "


class PromoteError(Exception):
    """昇格の入力エラー。"""


def load_registry(path: Path) -> dict:
    """ps_battlefields.js から JSON 部分を取り出す。"""
    text = path.read_text(encoding="utf-8")
    start = text.find(ASSIGN)
    if start < 0:
        raise PromoteError(f"{path}: '{ASSIGN}' が見つかりません")
    body = text[start + len(ASSIGN):].strip()
    if body.endswith(";"):
        body = body[:-1]
    try:
        return json.loads(body)
    except json.JSONDecodeError as exc:
        raise PromoteError(f"{path}: JSON 解析に失敗しました ({exc})")


def write_registry(path: Path, registry: dict) -> None:
    """同じ体裁で書き戻す。"""
    payload = json.dumps(registry, ensure_ascii=False, indent=2)
    path.write_text(HEADER + ASSIGN + payload + ";\n", encoding="utf-8")


def check_logical_match(name: str, live: dict, hd: dict) -> None:
    """論理座標がHD化で動いていないことを確認する。"""
    for key in ("imageWidth", "imageHeight"):
        if live.get(key) != hd.get(key):
            raise PromoteError(
                f"{name}: {key} が live={live.get(key)} / hd={hd.get(key)} で不一致。"
                " HD化で論理サイズが変わってはいけない。"
            )
    if live.get("projection") != hd.get("projection"):
        raise PromoteError(
            f"{name}: projection が不一致。HDだからと origin を2倍していないか確認すること。\n"
            f"  live={live.get('projection')}\n  hd  ={hd.get('projection')}"
        )
    if live.get("rows") != hd.get("rows"):
        raise PromoteError(f"{name}: rows(地形) が不一致。同一シードの再生成か確認すること。")


def main() -> int:
    parser = argparse.ArgumentParser(description="HD地面(2x)を本編へ昇格します。")
    parser.add_argument("--hd-dir", type=Path, default=Path("output/ground_hd_maps"))
    parser.add_argument("--maps-dir", type=Path, default=Path("asset/environment/maps"))
    parser.add_argument("--dry-run", action="store_true", help="書き込まずに結果だけ表示")
    args = parser.parse_args()

    live_path = args.maps_dir / "ps_battlefields.js"
    hd_path = args.hd_dir / "ps_battlefields.js"
    if not live_path.is_file():
        raise PromoteError(f"本編レジストリがありません: {live_path}")
    if not hd_path.is_file():
        raise PromoteError(f"HDレジストリがありません: {hd_path}")

    live = load_registry(live_path)
    hd = load_registry(hd_path)

    promoted, skipped, copied_bytes = [], [], 0

    for name, entry in live.items():
        hd_entry = hd.get(name + HD_SUFFIX)
        if hd_entry is None:
            skipped.append(name)
            continue

        check_logical_match(name, entry, hd_entry)

        src = args.hd_dir / f"{name}{HD_SUFFIX}.png"
        if not src.is_file():
            raise PromoteError(f"{name}: HD画像がありません: {src}")
        dst = args.maps_dir / src.name

        if not args.dry_run:
            shutil.copy2(src, dst)
        copied_bytes += src.stat().st_size

        entry["image"] = src.name
        entry["pixelRatio"] = int(hd_entry.get("pixelRatio", 2))
        promoted.append(name)

    if not args.dry_run:
        write_registry(live_path, live)

    print(f"昇格: {len(promoted)} マップ ({copied_bytes / 1024 / 1024:.1f} MB)")
    for name in promoted:
        print(f"  {name} -> {name}{HD_SUFFIX}.png (pixelRatio=2)")
    if skipped:
        print(f"据え置き(HD版なし): {', '.join(skipped)}")
    if args.dry_run:
        print("dry-run のため書き込みませんでした。")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PromoteError as exc:
        print(f"エラー: {exc}", file=sys.stderr)
        sys.exit(1)
